import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { Navbar } from "../components/NavBar";

const Home: NextPage = () => {
  const { isSignedIn, user } = useUser();
  console.log("index.tsx 7 isSignedIn, user:", isSignedIn, user);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center  "></main>
    </>
  );
};

export default Home;
